config:
  aws:region: us-east-1
  ? ynab-banco-industrial-connector.deploy:APPLICATION__BancoIndustrialMobileNotificationCreditCardAccountNameForEstablishmentTransactions
  : secure: AAABAFg1Irt/YPjVrlAjhBtFBdZBalYAnxfD4lpkCv+r25ceTy35hQ==
  ? ynab-banco-industrial-connector.deploy:APPLICATION__BancoIndustrialMobileNotificationDebitCardAccountNameForEstablishmentTransactions
  : secure: AAABABYtYLSOsdW41oDppIc7THBpIN3LPvPQuxMzzdx67nY+4XGSQk0=
  ynab-banco-industrial-connector.deploy:BANCO_INDUSTRIAL_SCRAPER__AccountId:
    secure: AAABAOqsXBJTT+tolvQnT1bpTUcCiIPs1KesErwAFDsAeC8ohi6T+SGW
  ynab-banco-industrial-connector.deploy:BANCO_INDUSTRIAL_SCRAPER__Auth__Password:
    secure: AAABANJEbxRroz8jgkAt5UJOID0C/uNC+mhjRKzacmhddJ57SSezU7RM8OSNvmA=
  ynab-banco-industrial-connector.deploy:BANCO_INDUSTRIAL_SCRAPER__Auth__UserId:
    secure: AAABAKXoQjH231od2+On3LUBR51hVXk+dK+79j4BO6JpN+EY2WbL
  ynab-banco-industrial-connector.deploy:BANCO_INDUSTRIAL_SCRAPER__Auth__Username:
    secure: AAABAGSGfpc3rZjU033VEqLwfmGglrmq3ecPZgLkJ+RdkcEgYA==
  ynab-banco-industrial-connector.deploy:BANCO_INDUSTRIAL_SCRAPER__PlaywrightServerUrl:
    secure: AAABAC2NKU09oguVFSLfZWp2E3MPP2gwgoh8JJ5I+DW1h2HpPTzKcngfLZkr26xzZpyBu/DtMQi107TjYtZJaYY8wPcktJFQYXneksJGKtqr8BVpHEWFPt/kjN8pR2uk
  ynab-banco-industrial-connector.deploy:YNAB__AccountId:
    secure: AAABAJu49rAtlIeLwcX4mtiIr2QjmcG4LLQUZTdv43d737lnoWA8Y371HEZ9qQQ4xnudclh4qmlBHD/+0Zlg7O1iQyE=
  ynab-banco-industrial-connector.deploy:YNAB__BudgetId:
    secure: AAABAHhNio1hUtj7eIWNRzxFaKoi6Ayc8unmIqvm2s95GZvvh8Gx9Ru/tVf2LI3VnxfKKce8lwtPHPXVhBAfzejncY8=
  ynab-banco-industrial-connector.deploy:YNAB__CreditCardAccountId:
    secure: AAABAEQv8u6Q7WMP0+GElSwSddziU13RKJ6FDMimSPIH9JR/OK3OIfIEoX8NYZ7o1MYRmXbTTgwZ8QqF54ySdBSU9v4=
  ynab-banco-industrial-connector.deploy:YNAB__DebitCardAccountId:
    secure: AAABAN8MzMUzTLTZ+PuRug/BwXKMEDmHqKjTQorVMxAe0OKS5KeaM0mnqDNYE44nvAAh2BI98NM+Q/JouxcWFqlLns8=
  ynab-banco-industrial-connector.deploy:YNAB__PersonalAccessToken:
    secure: AAABACFTY6f4KWBXZhSnxaKSkooa4du2FcQ5xizSm2+lhkMQx+w8cMuHupvPqxE6oQ3g3LDzJF3/dxMba4F4Ob6jZpZcdUbAbH9Xgj8ol97nzeXVK9CFSTtqTo+ZH9OX
